//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacnetLutronWeb.DataModal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BackNet_LutronEntities : DbContext
    {
        public BackNet_LutronEntities()
            : base("name=BackNet_LutronEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BACnetDevice> BACnetDevices { get; set; }
        public virtual DbSet<BACnetDeviceMapping> BACnetDeviceMappings { get; set; }
    }
}
