//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacnetLutronWeb.DataModal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACnetDeviceMapping
    {
        public int bacnet_device_mapping_id { get; set; }
        public Nullable<int> device_id { get; set; }
        public Nullable<int> object_instance { get; set; }
        public Nullable<int> floor_id { get; set; }
        public Nullable<int> suite_id { get; set; }
        public Nullable<int> room_id { get; set; }
    }
}
