//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacnetLutronWeb.DataModal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACnetDevice
    {
        public int bacnet_device_id { get; set; }
        public string network_id { get; set; }
        public Nullable<int> device_id { get; set; }
        public string object_type { get; set; }
        public Nullable<int> object_instance { get; set; }
        public string object_name { get; set; }
        public string routed_source { get; set; }
        public Nullable<int> routed_net { get; set; }
    }
}
